### ISSUE TITLE
No Night Lighting

### ISSUE THREAD

**Issue by cg49me** [webbukkit/dynmap#1725]
Night lighting doesn't seem to be working for me...

Here's a picture of a particular area during the "day":
![dmap_d](https://cloud.githubusercontent.com/assets/10518202/5793590/b5d7dfbe-9f17-11e4-8e47-5b64ed90a31b.jpg)

Here's the same area at "night":
![dmap_n](https://cloud.githubusercontent.com/assets/10518202/5793594/c952516e-9f17-11e4-9455-2ed90831678e.jpg)

At sunset/sunrise, I see the whole map "blink" like it's supposed to be switching between day/night, but it still looks the same.  Forgive the odd tiles - I've been experimenting with this trying to get it to work, and was in the middle of a fullrender.

I do all my map definitions inside worlds.txt.  Here's the pertinent section:

```
  - class: org.dynmap.hdmap.HDMap
    name: Iso30NEstddn
    title:  "Isometric View, NE, stdtexture, day/night"
    perspective: iso_SW_30_hires
    shader: stdtexture
    lighting: nightandday-smooth
    icon: images/block_surface.png
    mapzoomin: 0
```

Is there an "enable night" option somewhere in configuration.txt that I haven't found?  Is there another option required under the class header that I haven't included?

I'm using version 2.2-SNAPSHOT-2036 on a Forge 1.7.10 server, version 10.13.2.1286, with an obscene number of mods...

Thanks!

**Comment by Psy-Virus** [comment]
Can confirm it with `brightnightandday` lightning
but on my side some tiles are partially shaded.

### Day
![2015-01-18 22-36-54day](https://cloud.githubusercontent.com/assets/6222200/5794178/2fa2fb94-9f63-11e4-9303-fa23d145606d.png)
### Night
![2015-01-18 22-36-03night](https://cloud.githubusercontent.com/assets/6222200/5794179/3924c472-9f63-11e4-9e30-50fc5a50c2de.png)

**Comment by Cpt-Beefheart** [comment]
Confirmed!  & I'm glad it is not just me, I was just about to do attempt #8 and have exhausted any remaining ideas. 

ALSO can confirm that Dynmap is rendering a separate copy of the map (thus the map blinking at light change is switching between the two).  Both NAME folder and NAME_day folder are rendering full maps as day.  I tried with only a night map and only rendered a daytime lighting.

Also while at it, as per the pictures above by others, one of each sun and moon is not aligned properly with the time.
Thank you!

**Comment by cg49me** [comment]
On the sun and moon alignment, I think you're looking at the weather indicator (sun and moon to the right of the time in Psy-Virus' pics).  The actual "time" sun/moon indicator is to the left, and appears correct to me in all four above pics.

**Comment by Cpt-Beefheart** [comment]
Ah, apologies, I may be remembering incorrectly from a while ago.  Thought you could have the MC style sun/moon aligned with time changes.  Then as well as that, a storm cloud for storms, and nothing when clear.

**Comment by rdlenk** [comment]
Having the same problem. Also appears that the daylight map is not updating. Here is a picture of the night map after starting and canceling a full render.

![image](https://cloud.githubusercontent.com/assets/10699509/5893205/d45b3576-a48f-11e4-9e94-18545e7522c9.png)

I am running Spigot (git-Spigot-b1e6da1-1092acb, MC: 1.8, API version 1.8-R0.1-SNAPSHOT) and Dynmap (version: core=2.2-SNAPSHOT-2036, plugin=2.2-SNAPSHOT-1096) and only one other minor plugin. This started happening with the Dynmap 2.1 release and so i tried the 2.2 dev release but have the same problem. I am using 'brightnightandday-smooth' for lighting. Would be happy to provide any more details if needed.

**Comment by rdlenk** [comment]
Reverting to Dynmap core version 2.1-SNAPSHOT-2021, plugin version 2.1-SNAPSHOT-1077 (this was posted as Dymap-2.1-alpha-1) fixed the problem. The night map now looks right and the daylight map is rendering updates again.

**Comment by Black-Hole** [comment]
Disabling "use-brightness-table" in the config has the same effect.

**Comment by mikeprimm** [comment]
Check out latest 2.2 dev build - should be fixed.

**Comment by cg49me** [comment]
Just downloaded 2.2-SNAPSHOT-2041 and started a full render - that seems to have done it!  Thanks!

**Comment by RoyCurtis** [comment]
I believe this bug is still present; I am unable to get night rendering properly working.

### Details
(is this correct? plugin seems to mismatch core..)
```
[16:29:31 INFO]: Dynmap version: core=2.2-SNAPSHOT-2042, plugin=2.2-SNAPSHOT-1104
Mar 22 11:59 dynmap-HEAD.jar
```

* World configuration: https://gist.github.com/RoyCurtis/a89875ac94ca0d8ad27e
* Tried with both Surface and Night maps using `iso_SE_30_hires` perspective; the [Surface would become overwritten with night tiles](http://i.imgur.com/QP5eY2P.jpg) and the Night map would render as day. Incidentally, radius render would render both simultaneously:
 * `Radius render of maps [surface,night] of 'world' in progress - 100 tiles rendered each (12.15 msec/map-tile, 45.97 msec per render)`
* Tried with Surface set to `iso_SE_30_hires` and Night set to `iso_SE_30_medres`. Surface and Night render as day time, radius render does a map at a time
* Tested using `radiusrender` only
