### ISSUE TITLE
Dynmap having trouble with timezone.

### ISSUE THREAD

**Issue by Pingger** [webbukkit/dynmap#2447]
## Server Information

- I can reproduce this issue consistently
     - [x] In Multiplayer 
     - [x] After deleting/renaming the DYNMAP folder
- [x] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- I have tried the following diagnostics;
     - [ ] Re-rendered missing chunks using /dynmap fullrender (no database connection so fullrender only makes matters worse)
     - [ ] Cleared cached tiles using /dynmap purgeworld [world] (especially if using a map from an older version) (what should be cleared, when there is no database connection)
     - [x] Deleted/Renamed the dynmap folder to regenerate configs and files fresh
     - [x] Tested using the 'HEAD' version from dynmap.us/builds (these are stable to use)
     - [x] Rechecked the Minecraft Server and Webserver Config (If using an external Webserver)

## Issue Description
```
[23:52:17] [Server thread/INFO] [Dynmap]: [Dynmap] Web server started on address 127.0.0.1:3004
[23:52:17] [Server thread/INFO] [Dynmap]: [Dynmap] version 3.0-SNAPSHOT-170 is enabled - core version 3.0-SNAPSHOT-170
[23:52:17] [Server thread/INFO] [Dynmap]: [Dynmap] For support, visit https://forums.dynmap.us
[23:52:17] [Server thread/INFO] [Dynmap]: [Dynmap] To report or track bugs, visit https://github.com/webbukkit/dynmap/issues
[23:52:17] [Server thread/INFO] [Dynmap]: [Dynmap] Loaded 1 maps of world 'world'.
[23:52:17] [Server thread/INFO] [Dynmap]: [Dynmap] Loaded 1 maps of world 'DIM-11'.
[23:52:17] [Server thread/INFO] [Dynmap]: [Dynmap] Loaded 1 maps of world 'DIM1'.
[23:52:17] [Server thread/INFO] [Dynmap]: [Dynmap] Loaded 1 maps of world 'DIM-1'.
[23:52:17] [Server thread/INFO] [Dynmap]: [Dynmap] Loaded 1 maps of world 'DIM-2'.
[23:52:17] [Server thread/INFO] [Dynmap]: [Dynmap] Loaded 1 maps of world 'DIM-3'.
[23:52:17] [Server thread/INFO] [Dynmap]: [Dynmap] Loaded 2 pending tile renders for world 'world'
[23:52:17] [Server thread/INFO] [Dynmap]: [Dynmap] Register events
[23:52:17] [Server thread/INFO] [Dynmap]: [Dynmap] Register commands
[23:52:17] [Server thread/INFO] [Dynmap]: [Dynmap] Enabled
[23:52:17] [Server thread/INFO] [minecraft/DedicatedServer]: Dynmap reloaded
[23:52:17] [Server thread/WARN] [minecraft/MinecraftServer]: Can't keep up! Did the system time change, or is the server overloaded? Running 18519ms behind, skipping 370 tick(s)
[23:52:18] [Dynmap Render Thread/INFO] [Dynmap]: [Dynmap] Loading resource pack standard
[23:52:30] [Dynmap Render Thread/FATAL] [Dynmap]: [Dynmap] Error updating Maps table - The server time zone value 'MitteleuropÃ¤ische Sommerzeit' is unrecognized or represents more than one time zone. You must configure either the server
 or JDBC driver (via the serverTimezone configuration property) to use a more specifc time zone value if you want to utilize time zone support.
```

## Reproduce Steps
1. Start the server with just dynmap installed. (Forge Mod Loader version 14.23.5.2811)
2. Have an empty because the dynmap needs the timezone for WHATEVER?! to connect to the sql server?! 
...

## Additional Information
With spigot this works without any issues. But spigot also doesn't need the mysql connector library ...

**Comment by FedUpWith-Tech** [comment]
Assuming this is fixed in a later release or otherwise no longer relevant- please open a new issue if this persists.

**Comment by Pingger** [comment]
@FedUpWith-Tech The issue is still relevant and is still not fixed, instead it got worse!
Now it can't even connect to the database anymore.

Dynmap-Version:  3.1-SNAPSHOT-391
mysql-connector: mysql-connector-java-8.0.21
Forge: forge-1.15.2-31.2.33
```
[01Aug2020 21:01:10.817] [Server thread/INFO] [STDERR/]: [com.mysql.jdbc.Driver:<clinit>:43]: Loading class `com.mysql.jdbc.Driver'. This is deprecated. The new driver class is `com.mysql.cj.jdbc.Driver'. The driver is automatically registered via the SPI and manual loading of the driver class is generally unnecessary.
[01Aug2020 21:01:19.110] [Server thread/FATAL] [Dynmap/]: [Dynmap] Error creating tables - Could not create connection to database server. Attempted reconnect 3 times. Giving up.
[01Aug2020 21:01:19.111] [Server thread/FATAL] [Dynmap/]: [Dynmap] Map storage initialization failure
```
Other applications and even a small test code I wrote could connect effortlessly!

**Comment by FedUpWith-Tech** [comment]
Hey! sorry to hear this is still an issue but I'm glad you still care enough to get it fixed-

Can you pastebin your configuration.txt?

**Comment by Pingger** [comment]
https://pastebin.com/gqAEH36w

Essentially the default config, where
- listen port is changed to 1111 (as 8123 is blocked with the "production" server)
- storage settings changed to mysql. 
  - the given user and pass are correct. the given permissions are limited to the given database and only localhost allowed.
- the quality is changed to hires_boost_xhi

**Comment by DeathDragonAW** [comment]
I receive the exact same warning:

`[Server thread/WARN]: Loading class `com.mysql.jdbc.Driver'. This is deprecated. The new driver class is `com.mysql.cj.jdbc.Driver'. The driver is automatically registered via the SPI and manual loading of the driver class is generally unnecessary.`

Any solution for this?

> dynmap v3.2-beta-2-483
> Paper version git-Paper-112 (MC: 1.17.1)

**Comment by Pingger** [comment]
Nope, not really ... it is just one of those, if your database/java doesn't like dynmap it just doesn't work ...
Only workaround: don't use database, but filetree instead

**Comment by DeathDragonAW** [comment]
> Nope, not really ... it is just one of those, if your database/java doesn't like dynmap it just doesn't work ...
> Only workaround: don't use database, but filetree instead

Could this be an OpenJDK issue?

Also my dynmap seems to work properly, I just seem to have performance issues when there are like 5~6 ppl on the server and I'm not yet sure where it's coming from.

**Comment by Pingger** [comment]
It could, but I also know, that this issue occurs with the oracle JDK and JRE

**Comment by FedUpWith-Tech** [comment]
https://stackoverflow.com/questions/37719818/the-server-time-zone-value-aest-is-unrecognized-or-represents-more-than-one-ti

Reading this post it seems that the timezone issue was an issue with the JDBC connector bundled with Paper. This should be fixed now as that was updated several time since the original issue was submitted.

I'll again assume this issue is no longer relevant and close it. If it is still relevant please let me know if any other plugins work with sql- it sounds like a specific configuration issue with this system as it hasn't been reported anywhere else.
