### ISSUE TITLE
Levers rendered incorrectly

### ISSUE THREAD

**Issue by Aaron2550** [webbukkit/dynmap#3626]
**Issue Description:** Levers show up incorrectly on the map.

* **Dynmap Version:** Dynmap version: core=3.3-beta-4-617, plugin=3.3-beta-4-617
* **Server Version:** git-Paper-169 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 60e46ab)
* **Server Host (if applicable):** Selfhosted
* **Other Relevant Data/Screenshots:** See below
* **Steps to Replicate:** Place Levers in all 4 Directions, render Map, Observe Issue

 [x] *I have looked at all other issues and this is not a duplicate*  
 [x] *I have been able to replicate this*

![image](https://user-images.githubusercontent.com/24834067/150683036-24ccaf55-5f29-4a74-a9a4-7cf4f3dbe692.png)
![image](https://user-images.githubusercontent.com/24834067/150683093-2b6eeea1-bdce-4576-bd5a-e7e33bc27e87.png)
![image](https://user-images.githubusercontent.com/24834067/150683125-2bcf16ec-be7b-4f29-91aa-e3f2240a5e93.png)

**Comment by mikeprimm** [comment]
Fixed in SNAPSHOT 675+

**Comment by JurgenKuyper** [comment]
seems like sideways levers are not fixed yet (706)
![image](https://user-images.githubusercontent.com/45831568/152872565-765a8c8e-a880-4b20-9654-496fef12d0cc.png)
bottom is in-game top is in dynmap

**Comment by mikeprimm** [comment]
Fixed

**Comment by JurgenKuyper** [comment]
Confirmed, thanks! you are doing a great job on fixing the texture errors!
